fun a():
	let test = 10

fun b():
	let test = 10

fun c():
	let test = 10

fun d():
	let test = 10

fun e():
	let test = 10

fun f():
	let test = 10

fun g():
	let test = 10

fun h():
	let test = 10

fun i():
	let test = 10

fun j():
	let test = 10

fun test():
	let test: int = 20 + 10

	test = 30

	test = 10 + 20

	let test1 = 20 + 10

	test1 = 30

	test1 = 10 + 20

fun some(list: Array[int]):
	let x = 5

fun some(list: Array[float]):
	let x = 5

fun tick(delta: float):
	let x = 5
