extends Node as Test

let my_test: Test
let my_val: float = 30

fun a():
	let test = 10

fun b():
	let test = 10

fun c():
	let test = 10

fun d():
	let test = 10

fun e():
	let test = 10

fun f():
	let test = 10

fun g():
	let test = 10

fun h():
	let test = 10

fun i():
	let test = 10

fun j():
	let test = 10

fun test():
	let test: int = 20 + 10

	test = 30

	test = 10 + 20

	let test1 = 20 + 10

	test1 = 30

	test1 = 10 + 20

fun some(blah: float):
	let x = 5

fun some(blah: int):
	let x = 7

fun tick(delta: float):
	let first: int = 10
	let second: float = 20

	some(first)
	some(second)
